### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by mistotebe** [aeroo/aeroo_reports#54]
Hi,
looking over the source, you might be inadvertently infringing on OpenERP's license.

You licensed your code under the GPLv3 (and are aware of the switch from GPLv3 to AGPLv3 and mention it in the copyright header), yet the modules are a derived work based on AGPLv3 code (Odoo v8 new ORM has never been released under GPLv3), which is not something the AGPL permits.

From what I can see, your intention is to make sure that noone thinks they can use the Odoo license exception to apply to your code. Since the exception at https://www.odoo.com/page/legal only applies to code that Odoo have the right to relicense, AGPLv3 already gives you that power over any derived work and switching to it will not make your position any weaker, whereas at the moment you are open to Odoo trying to enforce their copyrights. Please note that while I have some understanding of the copyright law, I am not a lawyer.

Is there another reason you chose GPLv3? Can you consider fixing this problem by switching to AGPLv3 so that everyone can use the module without fear of losing the license to use Odoo?

**Comment by sraps** [comment]
Hello, @mistotebe !

First of all thank you for bringing this again to attention, this problem is long since known with TinyERP -> OpenERP -> Odoo.

There are multiple concerns about licences and the GPLv3 in particular, I will try to clear out only major of them...

* Originally TinyERP was released under GPL licence and neither featured any contribution agreement, nor other similar thing. So all the contributors were submitting all the work under assumption that they are doing this under GPL v3 and will have a right to use the whole code base under this version irrevocably (which is governed by GPL license).

* Company behind the OpenERP (now Odoo) made several failing attempts to release closed source derived works to OpenERP, which have shown their clear intention to bend the licensing at their own advantage - never asking or caring the public contributor opinion. Although many, including myself were expressing many doubts about these moves.

* Just a few people/contributors have clearly expressed will to give up their contributions and allow to re-licence to AGPL or any other branch.. There were quite more who did not agree, nobody cared to even rewrite the code "contaminated" by contributions. Though some code was rewritten as the consequence by some quite aggressive complaints , so they admitted that in fact they do not have rights to re-licence the code voluntarily.

* Plugin systems like Aeroo Reports are made upon clearly defined framework of OpenERP/Odoo, so they have clearly stated boundaries. 

* Like most public FOSS systems have been built including public contributions, likewise it is with Aeroo Reports and Aeroo Reports Library, which is partially fork of other's work and hence is a derived work, including features public contributions. All of original work Aeroo Reports have been forked off is GPLv3, including OpenERP.

We believe the re-licencing to AGPL was not lawfull and has been executed incorrectly. So we keep rights to use GPL v3 - releasing all of our modules under GPLv3.

We will not throw away our work just because someone does evidently wrong moves, tries to bend the licensing at their own state of mood, or by force from investors or whatever other reason. Odoo is derived work of work of others and they are note sole owners of source code, so they did not have the right to re-license, without even grace period.

**Comment by mistotebe** [comment]
Hi @sraps,
thanks for the response. I agree that what OpenERP did when relicensing the entire repository was not done as it should have been. However there can be no doubt that the new code is covered under AGPL and building on top of that code is enough to make a derived work of that, which has to be licensed under AGPL.

It is possible that if you cannot get the original GPL contributors of code in this repository to agree to the license change, you might actually be unable to distribute it at all.

Why do you think that relicensing the modules under the AGPL would be throwing your work away? You still do not lose any control over that code, or let OpenERP have more, on the contrary.

Another option is to wait until the relevant parts are released under the LGPL as advertised some time ago. That would let you keep the license as-is without any legal issues.

**Comment by sraps** [comment]
@mistotebe 
`` However there can be no doubt that the new code is covered under AGPL and building on top of that code is enough to make a derived work of that, which has to be licensed under AGPL.
``
1. Again, this is the doubtable that code which is wrongfully re-licensed, is now rightfully under AGPL. 
2. Aeroo Reports has been and is being built as a derived work of multiple other works, contributions etc. We are building upon our and other's systems all of which by our stand is still licensed under GPL v3. And absolutely most of whom is still standing on that they are licensed under GPL v3. I see no point bringing the system that is doubtfully licensed under AGPL, some parts of which was released as closed source, into prevailing position.
``
It is possible that if you cannot get the original GPL contributors of code in this repository to agree to the license change, you might actually be unable to distribute it at all.
``
I can state the same about Odoo, I encourage you to redirect this assumption/question primarily to the Odoo maintainer.
``
Why do you think that relicensing the modules under the AGPL would be throwing your work away? You still do not lose any control over that code, or let OpenERP have more, on the contrary.
``
1. Because we are not attempting to bend these licensing matters as we desire, or in this case some other company desire.
2. We can not ask that original copyright owners of code included in Aeroo Reports would have right to ask either removing the system / rewriting their code / not change license.

We do not have funds to rewrite it, so evidently it would mean throwing our work away. Would it be better?

** We try to play by rules, please do not ask us to violate other's people's rights just because somebody else does.**

P.S. I would be glad to have a chance to rework many parts of Aeroo Reports and improve the performance, probably to remove licensing issues, but we are limited in funds even to maintain as we would like it to. Just because most people take FOSS for granted.

I encourage considering donating some funds/time or both towards Aeroo Reports funded.

**Comment by mistotebe** [comment]
I'm not accusing you of anything, just concerned for the licensing issues of anyone using the system, since they create risk that is hard to ignore for us (however unlikely it may be that Odoo try and enforce the copyrights). I have also raised some GPL compliance issues with Odoo and try to get improvements everywhere whose code we use just because I think it benefits the community.

> We try to play by rules, please do not ask us to violate other's people's rights just because somebody else does.

If I suggested you change the license regardless of whether the original authors agree, it would certainly be contrary to what I am trying to achieve. I was not aware that was already tried and actually an issue.

I understand your frustration and we try to contribute fixes/improvements to the projects we use and will do the same once we get more familiar with aeroo.

**Comment by sraps** [comment]
Aeroo Reports Library is a fork of Relatorio project, parts of which have been rewritten/rewised to accomplish many technical goals.

Relatorio is being maintained by people behind Tryton project, which is in itself fork of TinyERP and is a competitor and rival of Odoo in many ways. So I am not even asking them to re-license, just because they explicitly requested some parts, they have contributed to TinyERP, removed, due to licence changes. So my guess, their answer would be similar. ;)

I personally think, that forcing everybody move to AGPL, just so that Odoo maintainer have option to sell "private use" exemption to AGPL is crippling in nature. __I suggest to stay with GPL, so that one who wishes to keep their own changes private, have an righteous option. This is rightful with GPL branch.__

BTW: Tryton in itself if GPL licensed, because they forked TinyERP and it "was" GPL licensed, then.

I guess, I am closing this issue.
