### ISSUE TITLE
[8.0] numeric fields in ODS report

### ISSUE THREAD

**Issue by alexis-via** [aeroo/aeroo_reports#78]
While I was developping an ODS aeroo report for intrastat (cf my module l10n_fr_intrastat_product_ods available on https://github.com/akretion/odoo-usability/tree/8.0/l10n_fr_intrastat_product_ods), I was confronted to the following problem : I didn't find a way to include the float/integer fields as a Numeric fields in the ODS file ; it is always considered as a text field (which prevents sum, formulas, etc...). I tried different things: force the cell type to numeric in the ODS template, force language, change decimal separator, ... but none of them worked.

Do you know a way to include a float/int fields as Numeric in an ODS report ? Is it possible with aeroo_reports ?

**Comment by sraps** [comment]
This is not a bug in aeroo_reports odoo module, please consult this issue instead:
https://github.com/aeroo/aeroolib/issues/7

**Comment by jjscarafia** [comment]
@alexis-via I've achive this using openoffice (openoffice4 in my case) instead of libreoffice to edit and save the files. Don't know why the difference but it works

**Comment by alexis-via** [comment]
@jjscarafia interesting remark ! I do use libreoffice ; I don't use openoffice (only libreoffice is packaged on Ubuntu)

**Comment by sraps** [comment]
@alexis-via @jjscarafia This is what I think, because Libreoffice uses experimental attribute, that seems not be used by OpenOffice.

**Comment by a0c** [comment]
@alexis-via @sraps 
I'm sorry for the OT, but how do you express formulas then?
> it is always considered as a text field (which prevents sum, formulas, etc...)

E.g. the simplest example:
=SUM(O10:O13)

The number of rows varies, so how do you set the range to sum?
Hyperlinks (if upon "10" and "13") seem to be stripped from the formula on saving the file.

SUM is just an example, of course, there are aeroo-specific ways to sum numbers up.
But in general: how do you pass varying arguments to office formulas?

**Comment by sraps** [comment]
@a0c 
Actually, you don't, this is a shortcoming for OO/LO Calc as such. There is no option to put, let's say whole column in formula. In this matter Excel is better. The other reason is that even if you would, Aeroo does not process cell's contents after generating them. Why? Just because it's too complicated, and it would take too much effort to implement and would be too slow. Ok, one would like to pipe document through Calc instance, even if format change is not necessary, but even then comes shortcoming with dynamic ranges of Calc. Hence the solution is to do all math inside Python.
